prometheusOperator:
  enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: devpassword
  service:
    type: ClusterIP
  ingress:
    enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    retention: 2d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true